---
# Attacker role: Kali machine with recon tools

- name: Create alias for server
  lineinfile:
    path: /etc/hosts
    line: '10.1.26.9 server'

- name: Ensure recon tools are installed
  apt:
    pkg:
      - nmap
      - ftp
    update_cache: yes
...
